export const GAME_SOCKET_MESSAGE = {
  GAME_ENDED: "GAME_ENDED",
  GAME_INFO: "GAME_INFO",
  GAME_SERVER_HANDOFF: "GAME_SERVER_HANDOFF",
  GAME_STARTED: "GAME_STARTED",
  GAME_UPDATED: "GAME_UPDATED",
  GAME__PLAYER: "GAME__PLAYER",
  START_GAME: "START_GAME",
};
